.

diff --git a/bin/mapreduce b/bin/mapreduce
--- a/bin/mapreduce
+++ b/bin/mapreduce
@@ -21,7 +21,11 @@ fi
 # Parse argument.  $1 is the first argument
 case $1 in
   "start")
-    if pgrep -f mapreduce &> /dev/null; then
+    if pgrep -f mapreduce-manager &> /dev/null; then
+        echo "Error: mapreduce-manager is already running"
+        exit 1
+    fi
+    if pgrep -f mapreduce-worker &> /dev/null; then
         echo "Error: mapreduce-manager is already running"
         exit 1
     fi
@@ -36,28 +40,25 @@ case $1 in
     ;;
 
   "status")
-    if pgrep -f mapreduce-manager &> /dev/null; then
-        echo "manager running"
-        if pgrep -f mapreduce-worker &> /dev/null; then
-            echo "worker running"
-            exit 0 
-        else
-            echo "worker not running"
-        fi 
-    else
+    if pgrep -f mapreduce-manager &> /dev/null && \
+       pgrep -f mapreduce-worker &> /dev/null; then
+      echo "manager running"
+      echo "worker running"
+      exit 0
+    fi
+    if ! pgrep -f "mapreduce-manager" &> /dev/null; then
         echo "manager not running"
-        if pgrep -f mapreduce-worker &> /dev/null; then
-            echo "worker running"
-        else
-            echo "worker not running"
-        fi 
+    fi
+    if ! pgrep -f "mapreduce-worker" &> /dev/null; then
+        echo "worker not running"
     fi
     exit 1
     ;;
 
   "stop")
     echo "Stopping mapreduce ..."
-    mapreduce-submit --shutdown --host localhost --port 6000 || true
+    set +o pipefail
+    mapreduce-submit --shutdown --host localhost --port 6000 2>/dev/null || true
     sleep 2  # give the Manager time to receive signal and send to Workers
     if pgrep -f mapreduce-manager &> /dev/null; then
         echo "killing mapreduce manager ..."
@@ -70,8 +71,37 @@ case $1 in
     ;;
 
   "restart")
-    ./bin/mapreduce stop
-    ./bin/mapreduce start
+    echo "Stopping mapreduce ..."
+    set +o pipefail
+    mapreduce-submit --shutdown --host localhost --port 6000 || true
+    sleep 2  # give the Manager time to receive signal and send to Workers
+    if pgrep -f mapreduce-manager &> /dev/null; then
+        echo "killing mapreduce manager ..."
+        pkill -f mapreduce-manager || true
+    fi
+    if pgrep -f mapreduce-worker &> /dev/null; then
+        echo "killing mapreduce worker ..."
+        pkill -f mapreduce-worker || true
+    fi
+    set -o pipefail
+    if pgrep -f mapreduce-manager &> /dev/null; then
+        echo "Error: mapreduce-manager is already running"
+        exit 1
+    fi
+    if pgrep -f mapreduce-worker &> /dev/null; then
+        echo "Error: mapreduce-manager is already running"
+        exit 1
+    fi
+    echo "starting mapreduce ..."
+    mkdir -p var/uploads
+    mkdir -p var/log
+    rm -f var/log/manager.log var/log/worker-6002.log var/log/worker-6001.log
+    mapreduce-manager --host localhost --port 6000 --logfile var/log/manager.log &
+    sleep 2  # give the Manager time to start
+    mapreduce-worker --host localhost --port 6001 --manager-host localhost --manager-port 6000 --logfile var/log/worker-6001.log &
+    mapreduce-worker --host localhost --port 6002 --manager-host localhost --manager-port 6000 --logfile var/log/worker-6002.log &
+
+
     ;;
   *)
 esac
